### ISSUE TITLE
重绘几次后卡顿

### ISSUE THREAD

**Issue by dzhydaniel** [TimChen44/WinFormCanvasDemo#1]
timCanvas1.SetCurrentLayer(CubeLayer);
            timCanvas1.Refresh();

重新绘制几次后，UI变得响应迟钝，应该从哪方面去解决？请帮忙指点一下

**Comment by TimChen44** [comment]
请检查有没有进行了大量无意义的重绘操作。

**Comment by dzhydaniel** [comment]
Canvas稍微做了一下修改，原先继承PictureBox，改成继承UserControl,  鼠标操作里的Refresh方法，改成Invalidate(true)
